### ISSUE TITLE
A paste with NA handling

### ISSUE THREAD

**Issue by dandermotj** [hadley/vctrs#39]
This might sound a bit out of scope but I think there's a place for this function somewhere. 

I'm trying to do something very simple, which is concatenate a bunch of character columns in a data frame. The go to is `tidyr::unite` but my data set has a lot of NA values. `unite` concatenates vectors with `paste`, which means the result will be full of "blah, NA, blah, ...". There's a discussion of this here tidyverse/tidyr#203. 

The simple solution is just to sub in a `paste` function that handled `NA`s and it seemed weird to me that this didn't already exist but googling just brought up more [discussion](https://stackoverflow.com/questions/13673894/suppress-nas-in-paste) with some hacky and slow pure R solutions. 

So I think there's a need for a low level `paste(..., sep = " ", collapse = NULL, na.rm = FALSE)` and maybe vctrs is that place?

**Comment by hadley** [comment]
String handling functions live in stringr

**Comment by Demetrio92** [comment]
`str_replace_na(c(NA, "abc", "def"), replacement='')`

(google led me here)

**Comment by jerrod30** [comment]
if you use str_c instead of paste0 it will omit NAs
